COL OWNER FOR A20
COL OBJECT_NAME FOR A80
COL OBJECT_TYPE FOR A10
COL SQL_STATMENT FOR A180
SET LINE 200 PAGES 99
prompt '(1):select statement for check attack dba_objects view' 
SELECT OWNER, '"'||OBJECT_NAME||'"' OBJECT_NAME,OBJECT_TYPE,TO_CHAR(CREATED, 'YYYY-MM-DD HH24:MI:SS') CREATED
    FROM DBA_OBJECTS
    WHERE OBJECT_NAME LIKE 'DBMS_CORE_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_SYSTEM_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_SUPPORT_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_STANDARD_FUN9%';
    
prompt '(2):select statement for check attack dba_objects view' 
SELECT '    DROP '||OBJECT_TYPE||' "'||OWNER||'"."'||OBJECT_NAME||'";' SQL_STATMENT
    FROM DBA_OBJECTS
    WHERE OBJECT_NAME LIKE 'DBMS_CORE_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_SYSTEM_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_SUPPORT_INTERNA%'
    OR OBJECT_NAME LIKE 'DBMS_STANDARD_FUN9%';

prompt '(3):select statement for check attack dba_jobs view'
COL LOG_USER FOR A20
COL WHAT FOR A120
SELECT JOB, LOG_USER, WHAT 
    FROM DBA_JOBS
    WHERE WHAT LIKE 'DBMS_STANDARD_FUN9%' ;
    
prompt '(4):select statement for check attack dba_jobs view'
SELECT '    -- Logon with '||LOG_USER||CHR(10)||'    EXEC DBMS_JOB.BROKEN ('||JOB||', ''TRUE'')'||CHR(10)||'    EXEC DBMS_JOB.REMOVE('||JOB||')' SQL_STATMENT
  FROM DBA_JOBS
  WHERE WHAT LIKE 'DBMS_STANDARD_FUN9%' ;
EXIT;

